/**
 * magicSystem.ts
 * Defines the elemental magic spell system for all 14 spirit types.
 *
 * Each element has 3 signature spells triggered by different events:
 *  - speaking  : cast when spirit begins talking
 *  - tap       : cast when user clicks the spirit
 *  - hover     : cast on hover-enter
 *  - idle      : periodic ambient cast (background magic)
 *  - excited / angry / happy / sad / ... : emotional reactive casts
 *
 * Spells are safe by design — particles fade before reaching 130px
 * from the spirit center, never covering important UI content.
 */

import { ElementType, EmotionType } from '../types/spirit.types';

// ── Types ─────────────────────────────────────────────────────────

export type ParticleShape = 'circle' | 'diamond' | 'leaf' | 'bolt' | 'square' | 'ring';

export type SpellTrajectory =
  | 'explode'    // 360° radial burst
  | 'burst-up'   // upper hemisphere burst
  | 'rise'       // float straight upward
  | 'rain'       // fall downward
  | 'spiral'     // outward spiral path
  | 'orbit';     // expand to ring radius then fade

export type SpellTrigger =
  | 'speaking'
  | 'hover'
  | 'tap'
  | 'idle'
  | 'excited'
  | 'angry'
  | 'happy'
  | 'sad'
  | 'surprised'
  | 'mysterious'
  | 'calm'
  | 'proud';

export interface SpellDef {
  id: string;
  name: string;
  /** Number of simultaneous particles */
  particleCount: number;
  shape: ParticleShape;
  colors: string[];
  trajectory: SpellTrajectory;
  /** Max travel distance in CSS px from spirit center */
  speedPx: number;
  /** [min, max] individual particle size in CSS px */
  sizePx: [number, number];
  /** Total animation duration in ms */
  durationMs: number;
  /** CSS box-shadow glow color — undefined = no glow */
  glowColor?: string;
  /** Which state changes fire this spell */
  triggers: SpellTrigger[];
  /** Minimum ms between consecutive idle casts of this spell */
  idleCooldownMs?: number;
}

// ── Spell Definitions per Element ────────────────────────────────

export const ELEMENT_SPELLS: Record<ElementType, SpellDef[]> = {
  fire: [
    {
      id: 'fire-ember',
      name: 'Ember Burst',
      particleCount: 8,
      shape: 'circle',
      colors: ['#FF6B35', '#FF4500', '#FFD700', '#FF8C00'],
      trajectory: 'explode',
      speedPx: 75,
      sizePx: [3, 7],
      durationMs: 1100,
      glowColor: '#FF6B35',
      triggers: ['speaking', 'tap', 'excited'],
    },
    {
      id: 'fire-stream',
      name: 'Flamethrower Stream',
      particleCount: 12,
      shape: 'circle',
      colors: ['#FF6B35', '#FF4500', '#FFD700', '#FF8C00'],
      trajectory: 'burst-up',
      speedPx: 80,
      sizePx: [2, 6],
      durationMs: 700,
      glowColor: '#FF6B35',
      triggers: ['idle'],
      idleCooldownMs: 8000,
    },
    {
      id: 'fire-burst',
      name: 'Flame Burst',
      particleCount: 10,
      shape: 'circle',
      colors: ['#FF2200', '#FF4500', '#FF8C00', '#FFD700'],
      trajectory: 'burst-up',
      speedPx: 100,
      sizePx: [4, 9],
      durationMs: 900,
      glowColor: '#FF4500',
      triggers: ['angry', 'hover'],
    },
    {
      id: 'fire-wave',
      name: 'Flame Wave',
      particleCount: 11,
      shape: 'diamond',
      colors: ['#FF6B35', '#FF4500', '#FFD700', '#FF8C00'],
      trajectory: 'burst-up',
      speedPx: 90,
      sizePx: [3, 8],
      durationMs: 1000,
      glowColor: '#FF6B35',
      triggers: ['hover', 'proud', 'happy'],
    },
    {
      id: 'fire-ring',
      name: 'Fire Ring',
      particleCount: 7,
      shape: 'ring',
      colors: ['#FF4500', '#FFD700', '#FF8C00'],
      trajectory: 'orbit',
      speedPx: 55,
      sizePx: [4, 9],
      durationMs: 2200,
      glowColor: '#FF8C00',
      triggers: ['idle', 'calm'],
      idleCooldownMs: 10000,
    },
  ],

  water: [
    {
      id: 'water-orbs',
      name: 'Water Orbs',
      particleCount: 6,
      shape: 'ring',
      colors: ['#4FC3F7', '#29B6F6', '#81D4FA', '#00BCD4'],
      trajectory: 'orbit',
      speedPx: 50,
      sizePx: [4, 9],
      durationMs: 2000,
      glowColor: '#4FC3F7',
      triggers: ['speaking', 'tap', 'happy'],
    },
    {
      id: 'water-rain',
      name: 'Healing Rain',
      particleCount: 8,
      shape: 'circle',
      colors: ['#29B6F6', '#4FC3F7', '#B3E5FC'],
      trajectory: 'rain',
      speedPx: 65,
      sizePx: [2, 5],
      durationMs: 1600,
      glowColor: '#29B6F6',
      triggers: ['idle', 'sad'],
      idleCooldownMs: 10000,
    },
    {
      id: 'water-burst',
      name: 'Tidal Burst',
      particleCount: 9,
      shape: 'circle',
      colors: ['#00BCD4', '#4FC3F7', '#29B6F6'],
      trajectory: 'explode',
      speedPx: 70,
      sizePx: [3, 7],
      durationMs: 1300,
      glowColor: '#00BCD4',
      triggers: ['excited', 'hover', 'angry'],
    },
    {
      id: 'water-whip',
      name: 'Water Whip',
      particleCount: 9,
      shape: 'circle',
      colors: ['#00BCD4', '#4FC3F7', '#29B6F6'],
      trajectory: 'spiral',
      speedPx: 80,
      sizePx: [2, 6],
      durationMs: 1100,
      glowColor: '#4FC3F7',
      triggers: ['angry', 'tap'],
    },
    {
      id: 'water-beam',
      name: 'Pressure Beam',
      particleCount: 7,
      shape: 'ring',
      colors: ['#29B6F6', '#B3E5FC', '#4FC3F7'],
      trajectory: 'rise',
      speedPx: 70,
      sizePx: [3, 7],
      durationMs: 1600,
      glowColor: '#29B6F6',
      triggers: ['calm', 'proud'],
    },
  ],

  ice: [
    {
      id: 'ice-crystals',
      name: 'Frost Crystals',
      particleCount: 8,
      shape: 'diamond',
      colors: ['#B3E5FC', '#E1F5FE', '#81D4FA', '#FFFFFF'],
      trajectory: 'explode',
      speedPx: 72,
      sizePx: [3, 7],
      durationMs: 1400,
      glowColor: '#B3E5FC',
      triggers: ['speaking', 'tap', 'excited'],
    },
    {
      id: 'ice-snow',
      name: 'Snow Spiral',
      particleCount: 9,
      shape: 'circle',
      colors: ['#E1F5FE', '#B3E5FC', '#FFFFFF'],
      trajectory: 'spiral',
      speedPx: 55,
      sizePx: [2, 5],
      durationMs: 2200,
      glowColor: '#B3E5FC',
      triggers: ['idle'],
      idleCooldownMs: 12000,
    },
    {
      id: 'ice-freeze',
      name: 'Freeze Burst',
      particleCount: 7,
      shape: 'diamond',
      colors: ['#E1F5FE', '#FFFFFF', '#B3E5FC'],
      trajectory: 'burst-up',
      speedPx: 85,
      sizePx: [3, 8],
      durationMs: 800,
      glowColor: '#E1F5FE',
      triggers: ['angry', 'hover'],
    },
    {
      id: 'ice-beam',
      name: 'Freezing Beam',
      particleCount: 7,
      shape: 'bolt',
      colors: ['#E1F5FE', '#B3E5FC', '#FFFFFF'],
      trajectory: 'rise',
      speedPx: 100,
      sizePx: [3, 7],
      durationMs: 900,
      glowColor: '#B3E5FC',
      triggers: ['angry', 'excited'],
    },
    {
      id: 'ice-spike',
      name: 'Ice Spike',
      particleCount: 5,
      shape: 'diamond',
      colors: ['#FFFFFF', '#E1F5FE', '#81D4FA'],
      trajectory: 'rise',
      speedPx: 95,
      sizePx: [4, 9],
      durationMs: 900,
      glowColor: '#E1F5FE',
      triggers: ['idle', 'tap'],
      idleCooldownMs: 12000,
    },
  ],

  wind: [
    {
      id: 'wind-gust',
      name: 'Air Gust',
      particleCount: 8,
      shape: 'circle',
      colors: ['#B2EBF2', '#80DEEA', '#E0F7FA', '#FFFFFF'],
      trajectory: 'explode',
      speedPx: 100,
      sizePx: [2, 5],
      durationMs: 750,
      glowColor: '#80DEEA',
      triggers: ['speaking', 'tap', 'excited'],
    },
    {
      id: 'wind-spiral',
      name: 'Tornado Swirl',
      particleCount: 10,
      shape: 'circle',
      colors: ['#B2EBF2', '#E0F7FA', '#80DEEA'],
      trajectory: 'spiral',
      speedPx: 70,
      sizePx: [1, 4],
      durationMs: 1800,
      glowColor: '#80DEEA',
      triggers: ['idle'],
      idleCooldownMs: 7000,
    },
    {
      id: 'wind-arc',
      name: 'Slicing Wind Arc',
      particleCount: 10,
      shape: 'diamond',
      colors: ['#E0F7FA', '#FFFFFF', '#B2EBF2'],
      trajectory: 'burst-up',
      speedPx: 130,
      sizePx: [2, 5],
      durationMs: 500,
      glowColor: '#80DEEA',
      triggers: ['hover', 'angry'],
    },
    {
      id: 'wind-blade',
      name: 'Wind Blade',
      particleCount: 10,
      shape: 'diamond',
      colors: ['#E0F7FA', '#FFFFFF', '#B2EBF2'],
      trajectory: 'burst-up',
      speedPx: 135,
      sizePx: [1, 4],
      durationMs: 500,
      glowColor: '#80DEEA',
      triggers: ['angry', 'tap'],
    },
    {
      id: 'wind-vortex',
      name: 'Vortex Pulse',
      particleCount: 8,
      shape: 'ring',
      colors: ['#B2EBF2', '#FFFFFF', '#80DEEA'],
      trajectory: 'orbit',
      speedPx: 60,
      sizePx: [2, 6],
      durationMs: 2000,
      glowColor: '#80DEEA',
      triggers: ['idle', 'mysterious'],
      idleCooldownMs: 8000,
    },
  ],

  soil: [
    {
      id: 'soil-rocks',
      name: 'Rock Shower',
      particleCount: 6,
      shape: 'circle',
      colors: ['#8D6E63', '#795548', '#BCAAA4'],
      trajectory: 'explode',
      speedPx: 55,
      sizePx: [4, 10],
      durationMs: 1500,
      glowColor: '#8D6E63',
      triggers: ['tap', 'angry', 'speaking'],
    },
    {
      id: 'soil-dust',
      name: 'Dust Cloud',
      particleCount: 9,
      shape: 'circle',
      colors: ['#A1887F', '#BCAAA4', '#D7CCC8'],
      trajectory: 'burst-up',
      speedPx: 45,
      sizePx: [4, 8],
      durationMs: 1800,
      glowColor: '#A1887F',
      triggers: ['idle', 'excited'],
      idleCooldownMs: 14000,
    },
    {
      id: 'soil-orbit',
      name: 'Stone Orbit',
      particleCount: 4,
      shape: 'circle',
      colors: ['#795548', '#6D4C41', '#8D6E63'],
      trajectory: 'orbit',
      speedPx: 45,
      sizePx: [5, 11],
      durationMs: 3000,
      glowColor: '#8D6E63',
      triggers: ['hover', 'happy'],
    },
    {
      id: 'soil-spike',
      name: 'Earth Spike',
      particleCount: 6,
      shape: 'square',
      colors: ['#795548', '#6D4C41', '#8D6E63'],
      trajectory: 'rise',
      speedPx: 65,
      sizePx: [5, 12],
      durationMs: 1200,
      glowColor: '#8D6E63',
      triggers: ['angry', 'tap'],
    },
    {
      id: 'soil-seismic',
      name: 'Seismic Wave',
      particleCount: 8,
      shape: 'ring',
      colors: ['#A1887F', '#8D6E63', '#BCAAA4'],
      trajectory: 'explode',
      speedPx: 70,
      sizePx: [4, 10],
      durationMs: 1800,
      glowColor: '#A1887F',
      triggers: ['excited', 'proud'],
    },
  ],

  trees: [
    {
      id: 'trees-thorn',
      name: 'Thorn Whip',
      particleCount: 8,
      shape: 'bolt',
      colors: ['#388E3C', '#1B5E20', '#2E7D32', '#4CAF50'],
      trajectory: 'burst-up',
      speedPx: 95,
      sizePx: [2, 6],
      durationMs: 700,
      glowColor: '#66BB6A',
      triggers: ['speaking', 'tap', 'happy'],
    },
    {
      id: 'trees-bloom',
      name: 'Petal Bloom',
      particleCount: 10,
      shape: 'circle',
      colors: ['#F48FB1', '#EC407A', '#A5D6A7', '#66BB6A'],
      trajectory: 'rise',
      speedPx: 55,
      sizePx: [3, 7],
      durationMs: 2200,
      glowColor: '#66BB6A',
      triggers: ['idle', 'excited'],
      idleCooldownMs: 10000,
    },
    {
      id: 'trees-vine',
      name: 'Vine Strike',
      particleCount: 6,
      shape: 'leaf',
      colors: ['#388E3C', '#2E7D32', '#66BB6A'],
      trajectory: 'explode',
      speedPx: 70,
      sizePx: [3, 8],
      durationMs: 1200,
      glowColor: '#66BB6A',
      triggers: ['angry', 'hover'],
    },
    {
      id: 'trees-root',
      name: 'Root Trap',
      particleCount: 8,
      shape: 'leaf',
      colors: ['#388E3C', '#2E7D32', '#1B5E20'],
      trajectory: 'rain',
      speedPx: 60,
      sizePx: [4, 9],
      durationMs: 1800,
      glowColor: '#66BB6A',
      triggers: ['angry', 'tap'],
    },
    {
      id: 'trees-seed',
      name: 'Seed Explosion',
      particleCount: 11,
      shape: 'circle',
      colors: ['#CDDC39', '#D4E157', '#A5D6A7', '#8BC34A'],
      trajectory: 'explode',
      speedPx: 85,
      sizePx: [2, 6],
      durationMs: 900,
      glowColor: '#A5D6A7',
      triggers: ['idle', 'happy'],
      idleCooldownMs: 10000,
    },
  ],

  lightning: [
    {
      id: 'lightning-bolt',
      name: 'Electric Bolt',
      particleCount: 10,
      shape: 'bolt',
      colors: ['#FFF176', '#FFEE58', '#FFD600', '#FFFFFF'],
      trajectory: 'explode',
      speedPx: 110,
      sizePx: [2, 6],
      durationMs: 550,
      glowColor: '#FFD600',
      triggers: ['speaking', 'tap', 'excited'],
    },
    {
      id: 'lightning-thunder',
      name: 'Thunder Strike',
      particleCount: 4,
      shape: 'circle',
      colors: ['#FFFFFF', '#FFF9C4', '#FFD600'],
      trajectory: 'rain',
      speedPx: 110,
      sizePx: [8, 16],
      durationMs: 600,
      glowColor: '#FFFFFF',
      triggers: ['idle', 'hover'],
      idleCooldownMs: 5000,
    },
    {
      id: 'lightning-chain',
      name: 'Chain Burst',
      particleCount: 12,
      shape: 'bolt',
      colors: ['#FFFFFF', '#FFF176', '#FFD600'],
      trajectory: 'burst-up',
      speedPx: 130,
      sizePx: [1, 5],
      durationMs: 450,
      glowColor: '#FFFFFF',
      triggers: ['angry'],
    },
    {
      id: 'lightning-plasma',
      name: 'Plasma Discharge',
      particleCount: 15,
      shape: 'circle',
      colors: ['#FFFFFF', '#FFF176', '#FFD600'],
      trajectory: 'explode',
      speedPx: 125,
      sizePx: [1, 5],
      durationMs: 450,
      glowColor: '#FFFFFF',
      triggers: ['excited', 'proud'],
    },
    {
      id: 'lightning-sphere',
      name: 'Electric Sphere',
      particleCount: 9,
      shape: 'ring',
      colors: ['#FFD600', '#FFEE58', '#FFFFFF'],
      trajectory: 'orbit',
      speedPx: 50,
      sizePx: [3, 8],
      durationMs: 1800,
      glowColor: '#FFD600',
      triggers: ['idle', 'calm'],
      idleCooldownMs: 6000,
    },
  ],

  dark: [
    {
      id: 'dark-tendrils',
      name: 'Shadow Tendrils',
      particleCount: 7,
      shape: 'circle',
      colors: ['#4A148C', '#6A1B9A', '#1A237E', '#12005e'],
      trajectory: 'spiral',
      speedPx: 60,
      sizePx: [4, 10],
      durationMs: 2000,
      glowColor: '#6A1B9A',
      triggers: ['speaking', 'tap'],
    },
    {
      id: 'dark-projectile',
      name: 'Darkness Projectile',
      particleCount: 9,
      shape: 'circle',
      colors: ['#1A237E', '#4A148C', '#0a0020'],
      trajectory: 'explode',
      speedPx: 85,
      sizePx: [4, 9],
      durationMs: 900,
      glowColor: '#4A148C',
      triggers: ['idle', 'mysterious'],
      idleCooldownMs: 9000,
    },
    {
      id: 'dark-blade',
      name: 'Shadow Blade',
      particleCount: 8,
      shape: 'diamond',
      colors: ['#12005e', '#1A237E', '#000000', '#0a0020'],
      trajectory: 'burst-up',
      speedPx: 100,
      sizePx: [3, 8],
      durationMs: 600,
      glowColor: '#4A148C',
      triggers: ['angry', 'hover', 'excited'],
    },
    {
      id: 'dark-fear',
      name: 'Fear Wave',
      particleCount: 8,
      shape: 'ring',
      colors: ['#4A148C', '#6A1B9A', '#1A237E'],
      trajectory: 'orbit',
      speedPx: 42,
      sizePx: [5, 13],
      durationMs: 3000,
      glowColor: '#4A148C',
      triggers: ['mysterious', 'calm'],
    },
    {
      id: 'dark-smoke',
      name: 'Black Smoke Explosion',
      particleCount: 10,
      shape: 'circle',
      colors: ['#000000', '#0a0020', '#12005e'],
      trajectory: 'explode',
      speedPx: 60,
      sizePx: [7, 15],
      durationMs: 1400,
      glowColor: '#4A148C',
      triggers: ['idle', 'sad'],
      idleCooldownMs: 11000,
    },
  ],

  light: [
    {
      id: 'light-radiance',
      name: 'Radiant Burst',
      particleCount: 10,
      shape: 'circle',
      colors: ['#FFFFFF', '#FFF9C4', '#FFF59D', '#FFFDE7'],
      trajectory: 'explode',
      speedPx: 85,
      sizePx: [3, 8],
      durationMs: 1000,
      glowColor: '#FFFFFF',
      triggers: ['speaking', 'tap', 'happy', 'excited'],
    },
    {
      id: 'light-sigil',
      name: 'Holy Orbit',
      particleCount: 8,
      shape: 'ring',
      colors: ['#FFF9C4', '#FFFFFF', '#FFF59D'],
      trajectory: 'orbit',
      speedPx: 42,
      sizePx: [3, 7],
      durationMs: 2500,
      glowColor: '#FFFFFF',
      triggers: ['idle', 'calm'],
      idleCooldownMs: 8000,
    },
    {
      id: 'light-wave',
      name: 'Holy Wave',
      particleCount: 11,
      shape: 'circle',
      colors: ['#FFFFFF', '#FFF9C4'],
      trajectory: 'burst-up',
      speedPx: 100,
      sizePx: [2, 6],
      durationMs: 750,
      glowColor: '#FFFFFF',
      triggers: ['angry', 'hover', 'proud'],
    },
    {
      id: 'light-spear',
      name: 'Light Spear',
      particleCount: 6,
      shape: 'diamond',
      colors: ['#FFFFFF', '#FFFDE7', '#FFF9C4'],
      trajectory: 'rise',
      speedPx: 115,
      sizePx: [3, 8],
      durationMs: 700,
      glowColor: '#FFFFFF',
      triggers: ['tap', 'proud'],
    },
    {
      id: 'light-purify',
      name: 'Purification Wave',
      particleCount: 10,
      shape: 'ring',
      colors: ['#FFFFFF', '#FFF9C4', '#FFD600'],
      trajectory: 'explode',
      speedPx: 75,
      sizePx: [3, 8],
      durationMs: 1300,
      glowColor: '#FFFFFF',
      triggers: ['calm', 'happy'],
    },
  ],

  healing: [
    {
      id: 'healing-wave',
      name: 'Healing Wave',
      particleCount: 9,
      shape: 'ring',
      colors: ['#F48FB1', '#A5D6A7', '#80CBC4', '#FCE4EC'],
      trajectory: 'burst-up',
      speedPx: 60,
      sizePx: [4, 9],
      durationMs: 1200,
      glowColor: '#F48FB1',
      triggers: ['speaking', 'happy', 'idle'],
      idleCooldownMs: 9000,
    },
    {
      id: 'healing-beam',
      name: 'Restoration Beam',
      particleCount: 8,
      shape: 'ring',
      colors: ['#A5D6A7', '#80CBC4', '#F48FB1'],
      trajectory: 'rise',
      speedPx: 75,
      sizePx: [3, 7],
      durationMs: 1200,
      glowColor: '#A5D6A7',
      triggers: ['tap', 'sad', 'hover'],
    },
    {
      id: 'healing-pulse',
      name: 'Healing Pulse',
      particleCount: 7,
      shape: 'ring',
      colors: ['#FCE4EC', '#F8BBD0', '#FFFFFF'],
      trajectory: 'explode',
      speedPx: 60,
      sizePx: [4, 9],
      durationMs: 1200,
      glowColor: '#F48FB1',
      triggers: ['excited'],
    },
    {
      id: 'healing-regen',
      name: 'Regen Field',
      particleCount: 8,
      shape: 'ring',
      colors: ['#F8BBD0', '#A5D6A7', '#80CBC4'],
      trajectory: 'orbit',
      speedPx: 38,
      sizePx: [4, 9],
      durationMs: 3000,
      glowColor: '#F48FB1',
      triggers: ['idle', 'calm'],
      idleCooldownMs: 10000,
    },
    {
      id: 'healing-life',
      name: 'Life Burst',
      particleCount: 10,
      shape: 'circle',
      colors: ['#66BB6A', '#A5D6A7', '#F48FB1', '#FCE4EC'],
      trajectory: 'explode',
      speedPx: 65,
      sizePx: [3, 8],
      durationMs: 1100,
      glowColor: '#A5D6A7',
      triggers: ['excited', 'tap'],
    },
  ],

  void: [
    {
      id: 'void-sphere',
      name: 'Void Sphere',
      particleCount: 5,
      shape: 'circle',
      colors: ['#1a0030', '#0a0020', '#4A148C'],
      trajectory: 'orbit',
      speedPx: 38,
      sizePx: [6, 13],
      durationMs: 3000,
      glowColor: '#7B1FA2',
      triggers: ['speaking', 'tap', 'mysterious'],
    },
    {
      id: 'void-collapse',
      name: 'Gravity Pull',
      particleCount: 8,
      shape: 'circle',
      colors: ['#4A148C', '#1A0030', '#000000'],
      trajectory: 'spiral',
      speedPx: 50,
      sizePx: [4, 10],
      durationMs: 2000,
      glowColor: '#6A1B9A',
      triggers: ['idle', 'calm'],
      idleCooldownMs: 15000,
    },
    {
      id: 'void-tear',
      name: 'Reality Tear',
      particleCount: 6,
      shape: 'diamond',
      colors: ['#12005e', '#4A148C', '#000000'],
      trajectory: 'explode',
      speedPx: 80,
      sizePx: [3, 9],
      durationMs: 1100,
      glowColor: '#4A148C',
      triggers: ['angry', 'hover', 'excited'],
    },
    {
      id: 'void-nullify',
      name: 'Nullification Wave',
      particleCount: 7,
      shape: 'ring',
      colors: ['#1a0030', '#0a0020', '#4A148C'],
      trajectory: 'burst-up',
      speedPx: 65,
      sizePx: [4, 11],
      durationMs: 2000,
      glowColor: '#7B1FA2',
      triggers: ['hover', 'calm'],
    },
    {
      id: 'void-fracture',
      name: 'Reality Fracture',
      particleCount: 8,
      shape: 'diamond',
      colors: ['#4A148C', '#12005e', '#000000'],
      trajectory: 'explode',
      speedPx: 90,
      sizePx: [3, 9],
      durationMs: 900,
      glowColor: '#4A148C',
      triggers: ['angry', 'surprised'],
    },
  ],

  space: [
    {
      id: 'space-stars',
      name: 'Star Explosion',
      particleCount: 10,
      shape: 'circle',
      colors: ['#FFFFFF', '#7986CB', '#5C6BC0', '#B39DDB'],
      trajectory: 'explode',
      speedPx: 90,
      sizePx: [2, 6],
      durationMs: 1200,
      glowColor: '#7986CB',
      triggers: ['speaking', 'tap', 'excited'],
    },
    {
      id: 'space-grav-orb',
      name: 'Gravitational Orb',
      particleCount: 6,
      shape: 'circle',
      colors: ['#CE93D8', '#7986CB', '#B39DDB'],
      trajectory: 'orbit',
      speedPx: 45,
      sizePx: [5, 11],
      durationMs: 3200,
      glowColor: '#CE93D8',
      triggers: ['idle', 'calm'],
      idleCooldownMs: 10000,
    },
    {
      id: 'space-beam',
      name: 'Cosmic Beam',
      particleCount: 11,
      shape: 'circle',
      colors: ['#FFFFFF', '#B39DDB', '#7986CB'],
      trajectory: 'burst-up',
      speedPx: 110,
      sizePx: [1, 5],
      durationMs: 800,
      glowColor: '#B39DDB',
      triggers: ['hover', 'angry', 'happy'],
    },
    {
      id: 'space-meteor',
      name: 'Meteor Storm',
      particleCount: 11,
      shape: 'circle',
      colors: ['#FFFFFF', '#B39DDB', '#EF9A9A'],
      trajectory: 'rain',
      speedPx: 105,
      sizePx: [2, 7],
      durationMs: 900,
      glowColor: '#B39DDB',
      triggers: ['angry', 'excited'],
    },
    {
      id: 'space-nebula',
      name: 'Nebula Burst',
      particleCount: 10,
      shape: 'circle',
      colors: ['#CE93D8', '#7986CB', '#4FC3F7', '#B39DDB'],
      trajectory: 'spiral',
      speedPx: 65,
      sizePx: [3, 8],
      durationMs: 2500,
      glowColor: '#7986CB',
      triggers: ['idle', 'happy'],
      idleCooldownMs: 10000,
    },
  ],

  time: [
    {
      id: 'time-fracture',
      name: 'Temporal Fracture',
      particleCount: 8,
      shape: 'diamond',
      colors: ['#ECEFF1', '#B0BEC5', '#90A4AE', '#CFD8DC'],
      trajectory: 'explode',
      speedPx: 90,
      sizePx: [3, 8],
      durationMs: 1000,
      glowColor: '#90A4AE',
      triggers: ['speaking', 'idle', 'mysterious'],
      idleCooldownMs: 11000,
    },
    {
      id: 'time-rewind',
      name: 'Temporal Rewind',
      particleCount: 8,
      shape: 'diamond',
      colors: ['#CFD8DC', '#B0BEC5', '#ECEFF1'],
      trajectory: 'spiral',
      speedPx: 65,
      sizePx: [2, 6],
      durationMs: 2000,
      glowColor: '#B0BEC5',
      triggers: ['tap', 'excited', 'hover'],
    },
    {
      id: 'time-freeze',
      name: 'Time Freeze',
      particleCount: 7,
      shape: 'diamond',
      colors: ['#ECEFF1', '#CFD8DC', '#B0BEC5'],
      trajectory: 'explode',
      speedPx: 70,
      sizePx: [3, 7],
      durationMs: 1500,
      glowColor: '#90A4AE',
      triggers: ['angry', 'surprised'],
    },
    {
      id: 'time-afterimage',
      name: 'Afterimage Trail',
      particleCount: 6,
      shape: 'ring',
      colors: ['#B0BEC5', '#CFD8DC', '#ECEFF1'],
      trajectory: 'orbit',
      speedPx: 40,
      sizePx: [5, 12],
      durationMs: 3200,
      glowColor: '#90A4AE',
      triggers: ['idle', 'calm'],
      idleCooldownMs: 12000,
    },
    {
      id: 'time-accel',
      name: 'Time Acceleration',
      particleCount: 10,
      shape: 'diamond',
      colors: ['#ECEFF1', '#CFD8DC', '#B0BEC5'],
      trajectory: 'burst-up',
      speedPx: 110,
      sizePx: [2, 6],
      durationMs: 700,
      glowColor: '#B0BEC5',
      triggers: ['tap', 'excited'],
    },
  ],

  robot: [
    {
      id: 'robot-laser',
      name: 'Laser Pulse',
      particleCount: 8,
      shape: 'square',
      colors: ['#00E5FF', '#18FFFF', '#00B8D4', '#84FFFF'],
      trajectory: 'explode',
      speedPx: 95,
      sizePx: [2, 6],
      durationMs: 750,
      glowColor: '#00E5FF',
      triggers: ['speaking', 'tap', 'excited'],
    },
    {
      id: 'robot-cannon',
      name: 'Energy Cannon',
      particleCount: 8,
      shape: 'square',
      colors: ['#00E5FF', '#18FFFF', '#00B8D4'],
      trajectory: 'burst-up',
      speedPx: 130,
      sizePx: [4, 10],
      durationMs: 550,
      glowColor: '#00E5FF',
      triggers: ['idle', 'hover'],
      idleCooldownMs: 6000,
    },
    {
      id: 'robot-digital',
      name: 'Digital Burst',
      particleCount: 12,
      shape: 'square',
      colors: ['#00E5FF', '#FFFFFF', '#18FFFF'],
      trajectory: 'burst-up',
      speedPx: 105,
      sizePx: [1, 5],
      durationMs: 650,
      glowColor: '#00E5FF',
      triggers: ['angry', 'hover'],
    },
    {
      id: 'robot-drone',
      name: 'Drone Beam',
      particleCount: 6,
      shape: 'square',
      colors: ['#00E5FF', '#84FFFF', '#18FFFF'],
      trajectory: 'rise',
      speedPx: 80,
      sizePx: [3, 7],
      durationMs: 1200,
      glowColor: '#00E5FF',
      triggers: ['idle', 'hover'],
      idleCooldownMs: 7000,
    },
    {
      id: 'robot-hologram',
      name: 'Hologram Ring',
      particleCount: 9,
      shape: 'ring',
      colors: ['#00E5FF', '#FFFFFF', '#84FFFF'],
      trajectory: 'orbit',
      speedPx: 45,
      sizePx: [3, 8],
      durationMs: 2500,
      glowColor: '#00E5FF',
      triggers: ['mysterious', 'calm'],
    },
  ],
};

/** Map emotion state to the closest spell trigger. */
export const EMOTION_TRIGGER_MAP: Partial<Record<EmotionType, SpellTrigger>> = {
  excited:    'excited',
  angry:      'angry',
  happy:      'happy',
  sad:        'sad',
  surprised:  'surprised',
  mysterious: 'mysterious',
  calm:       'calm',
  proud:      'proud',
};

/** Return all spells for an element that match a given trigger. */
export function getSpellsForTrigger(element: ElementType, trigger: SpellTrigger): SpellDef[] {
  return (ELEMENT_SPELLS[element] ?? []).filter((s) => s.triggers.includes(trigger));
}
